#!/usr/bin/env python3

import asyncio

async_generator = __import__('0-async_generator').async_generator

async def print_yielded_values() -> None:
    """
    Collects and prints values yielded by the async_generator coroutine.

    This function asynchronously collects all values generated by
    async_generator into a list and prints the list after all values
    have been generated.
    """
    result = []
    async for value in async_generator():
        result.append(value)
    print(result)

asyncio.run(print_yielded_values())
