#!/usr/bin/env python3

import asyncio

async_generator = __import__('0-async_generator').async_generator

async def print_yielded_values() -> None:
    """
    Asynchronously collects and prints values yielded by async_generator.

    This function collects all values generated by the async_generator
    coroutine into a list and prints the list after all values have been
    generated.
    """
    result = []
    async for value in async_generator():
        result.append(value)
    print(result)

asyncio.run(print_yielded_values())
