#!/usr/bin/env python3

import asyncio
from typing import List

# Import the async_generator coroutine from the previous module

async_generator = __import__('0-async_generator').async_generator
async def async_comprehension() -> List[float]:
    """
    Collects 10 random numbers using asynchronous comprehension.

    This coroutine asynchronously collects numbers generated by the
    async_generator coroutine into a list and returns the list of these
    numbers.

    Returns:
        List[float]: A list of 10 random float values between 0 and 10.
    """
    return [number async for number in async_generator()]
